### ISSUE TITLE
mkldnn compilation error: protected function not accessible 

### ISSUE THREAD

**Issue by luohaibiao** [01org/mkl-dnn#53] opened 2017-04-27 09:21 UTC
During compilation of the latest Intel Caffe, mkldnn was downloaded and compiled with the following error:
/HOME/caffe-master/external/mkldnn/src/include/mkldnn.hpp(103): error #453: protected function "mkldnn::handle<T, traits>::handle(T, bool) [with T=mkldnn::c_api::mkldnn_primitive_t, traits=mkldnn::handle_traits<mkldnn::c_api::mkldnn_primitive_t>]" (declared at line 61) is not accessible through a "mkldnn::handle<mkldnn::c_api::mkldnn_primitive_t, mkldnn::handle_traits<mkldnn::c_api::mkldnn_primitive_t>>" pointer or object
      using handle::handle;
      ^
In file included from /HOME/caffe-master/external/mkldnn/src/examples/simple_training_net.cpp(20):
          detected during implicit generation of "mkldnn::primitive::primitive(mkldnn::c_api::mkldnn_primitive_t, bool)" at line 147
In file included from /HOME/ /caffe-master/external/mkldnn/src/examples/simple_training_net.cpp(20):

In Makefile.config of caffe-master, I have defined the CXX-COMPILER
CUSTOM_CXX := /HOME/intel/composer_xe_2015.1.133/bin/intel64/icpc

Before caffe-master/make, I type “export cc=/HOME/intel/composer_xe_2015.1.133/bin/intel64/icc"

It first downloaded and installed mklml_lnx_2017.0.2.20170110.tgz in caffe-master/external/mkl without any problem, then downloaded, installed  https://github.com/01org/mkl-dnn/releases/download/v0.7/mklml_lnx_2017.0.2.20170209.tgz. and stop at the above error

Note that I’m installing Intel Caffe in a supercomputer. The environment packages were loaded by module. 

Any suggestions on how to fix this problem?

**Comment by rsdubtso** [comment] 2017-04-27 09:25
MKL-DNN does not support 2015 compiler. Can you try something newer?

**Comment by luohaibiao** [comment] 2017-04-27 14:03
OK，I will try install 2017 compiler

**Comment by luohaibiao** [comment] 2017-05-04 06:02
Installed parallel_studio_xe_2017_update3, and add the source the installation paths into .bashrc
source /HOME/Intel_2017_3/bin/compilervars.sh intel64
source /HOME/Intel_2017_3/compilers_and_libraries_2017.3.191/linux/mkl/bin/mklvars.sh intel64 ilp64


Change the CXX_COMPILER in caffe-master/Makefile.config accordingly, 
Question 1: "caffe-master/make all" still reported errors in mkldnn:
[ 39%] Linking CXX shared library libmkldnn.so
make[3]: Leaving directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
[ 39%] Built target mkldnn
make[3]: Entering directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
make[3]: Leaving directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
make[3]: Entering directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
[ 40%] Building CXX object examples/CMakeFiles/simple-training-net-cpp.dir/simple_training_net.cpp.o
[ 40%] Linking CXX executable simple-training-net-cpp
../src/libmkldnn.so: undefined reference to `__cxa_throw_bad_array_new_length'
make[3]: *** [examples/simple-training-net-cpp] Error 1
make[3]: Leaving directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
make[2]: *** [examples/CMakeFiles/simple-training-net-cpp.dir/all] Error 2
make[2]: Leaving directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/WORK/Intel_caffe/caffe-master/external/mkldnn/build'
make: *** [mkldnn_build] Error 2

Any idea what went wrong? 

Question 2:
Another question, in "caffe-master/make all", the cmake command messages after mkldnn.commit is:
cmake external/mkldnn/src -DCMAKE_INSTALL_PREFIX=/WORK/Intel_caffe/caffe-master/external/mkldnn/install -B/WORK/Intel_caffe/caffe-master/external/mkldnn/build -DCMAKE_CXX_COMPILER="/HOME/Intel_2017_3/bin/icpc" -DCMAKE_C_COMPILER="cc"

Notice that:
-- The C compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc

The caffe-master/Makefile.config doesn't have a place to define C compiler. So it must be a Makefile in mkldnn folder that defines C compiler. However, I cannot find it under mkldnn folder.

**Comment by vpirogov** [comment] 2017-05-04 22:20
You need to tell CMake what compiler you want it to use using environment variables. When building with Intel compiler say
`CXX=icpc CC=icc cmake ..`

Unless you do this Cmake will be using system compiler, which happens to be an unsupported GCC 4.4.7 in your case.

Please let me know if this works for you.

**Comment by luohaibiao** [comment] 2017-05-05 02:13
Thanks, vpirogov. I did what you suggested: export cc=icc before make all, however, the same error: ../src/libmkldnn.so: undefined reference to `__cxa_throw_bad_array_new_length' still pop up in compilation of mkldnn

**Comment by vpirogov** [comment] 2017-05-05 14:15
You need to do both actually, CXX=icpc and CC=icc. Could you please also post full CMake output?

**Comment by luohaibiao** [comment] 2017-05-09 02:45
The make output file is attached.
The compiling error occurred at:
[ 40%] Linking CXX executable simple-training-net-cpp
../src/libmkldnn.so: undefined reference to `__cxa_throw_bad_array_new_length'

From the following debugging, we guess the problem is that cmake cannot load libstdc++.so if GCC is NOT installed at the default location. If there is a place in make file to tell cmake to load libstdc++.so from the right place, the error should be solved.

Note that we've done the following debugging and successfully compile simple-training-net-cpp;
$cat CMakeFiles/simple-training-net-cpp.dir/link.txt
/HOME/ac_iscas_hbluo_1/Intel_2017_3/bin/icpc    -fstack-protector  -fPIC -Wformat -Wformat-security -fopenmp -Wall -Werror -Wno-unknown-pragmas -DMKLDNN_DLL -DMKLDNN_DLL_EXPORTS -fvisibility=internal -std=c++11 -fvisibility-inlines-hidden -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -xHOST   -pie -z noexecstack -z relro -z now CMakeFiles/simple-training-net-cpp.dir/simple_training_net.cpp.o  -o simple-training-net-cpp  -L/HOME/ac_iscas_hbluo_1/local/anaconda3/lib -rdynamic ../src/libmkldnn.so -lm -lmkl_rt -Wl,-rpath,/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build/src:/HOME/ac_iscas_hbluo_1/local/anaconda3/lib

If we changed the above command to the following:
/HOME/ac_iscas_hbluo_1/Intel_2017_3/bin/icpc    -fstack-protector  -fPIC -Wformat -Wformat-security -fopenmp -Wall -Werror -Wno-unknown-pragmas -DMKLDNN_DLL -DMKLDNN_DLL_EXPORTS -fvisibility=internal -std=c++11 -fvisibility-inlines-hidden -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -xHOST   -pie -z noexecstack -z relro -z now CMakeFiles/simple-training-net-cpp.dir/simple_training_net.cpp.o  -o simple-training-net-cpp  -rdynamic ../src/libmkldnn.so -lm -lmkl_rt -Wl,-rpath,/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build/src:/HOME/ac_iscas_hbluo_1/local/anaconda3/lib

（Deleted: -L/HOME/ac_iscas_hbluo_1/local/anaconda3/lib）

OR

 /HOME/ac_iscas_hbluo_1/Intel_2017_3/bin/icpc    -fstack-protector  -fPIC -Wformat -Wformat-security -fopenmp -Wall -Werror -Wno-unknown-pragmas -DMKLDNN_DLL -DMKLDNN_DLL_EXPORTS -fvisibility=internal -std=c++11 -fvisibility-inlines-hidden -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -xHOST   -pie -z noexecstack -z relro -z now CMakeFiles/simple-training-net-cpp.dir/simple_training_net.cpp.o  -o simple-training-net-cpp **-L/WORK/app/gcc/4.9.2/lib64** -L/HOME/ac_iscas_hbluo_1/local/anaconda3/lib -rdynamic ../src/libmkldnn.so -lm -lmkl_rt -Wl,-rpath,/WORK/ac_iscas_hbluo_1/Intel_caffe/caffe-master_bk/external/mkldnn/build/src:/HOME/ac_iscas_hbluo_1/local/anaconda3/lib

Then it can be compiled through.

[cmake_output.txt](https://github.com/01org/mkl-dnn/files/985406/cmake_output.txt)

**Comment by vpirogov** [comment] 2017-05-09 16:16
libstdc++ dependency in normal scenario is resolved by ICC. The fact that it does not happen likely means that ICC cannot find libstdc++ or the environment is not configured properly. Do yo have /WORK/app/gcc/4.9.2/lib64 in your LD_LIBRARY_PATH before CMake call?

Error in question 2 is caused by defect in googlenet. This issue is already fixed in commit ab84d723f1988c4b11877e320182aa59428839b3.

**Comment by luohaibiao** [comment] 2017-05-11 08:54
Thanks, vpirogov. The problems have been solved. 

The reason for the first problem (error in compiling simple-training-net-cpp.dir) is that it loaded the wrong so library of anaconda3/lib/libmkl_rt.so. In Makefile.config of caffe-master, I changed the python_lib from anaconda3 to python 2.4.9 then this errror disappeared.

The problem 2 is now solved by the commit you suggested.

**Comment by vpirogov** [comment] 2017-05-11 23:35
Glad to hear that your issue is resolved!

**Closed by vpirogov** 2017-05-11 23:35 UTC
Labels: question

**Comment by lilytranx** [comment] 2019-04-17 20:47
Hi,
Do you have any idea about below error when compile caffe on the mkldnn:
home/gmah/Documents/caffe/external/mkldnn/src/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/gmah/Documents/caffe/external/mkldnn/src/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/gmah/Documents/caffe/external/mkldnn/src/src/cpu/ref_rnn.hpp:30,
                 from /home/gmah/Documents/caffe/external/mkldnn/src/src/cpu/ref_rnn.cpp:39:
/opt/intel/compilers_and_libraries_2019.3.199/linux/mkl/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
cc1plus: all warnings being treated as errors
src/CMakeFiles/mkldnn.dir/build.make:350: recipe for target 'src/CMakeFiles/mkldnn.dir/cpu/ref_rnn.cpp.o' failed
make[3]: *** [src/CMakeFiles/mkldnn.dir/cpu/ref_rnn.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/gmah/Documents/caffe/external/mkldnn/build'
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/mkldnn.dir/all' failed
make[2]: *** [src/CMakeFiles/mkldnn.dir/all] Error 2
make[2]: Leaving directory '/home/gmah/Documents/caffe/external/mkldnn/build'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/gmah/Documents/caffe/external/mkldnn/build'
Makefile.mkldnn:51: recipe for target 'mkldnn_build' failed

**Comment by emfomenk** [comment] 2019-04-17 21:12
Hi @lilytranx,

It seems you use the newer version of Intel MKL but older version of Intel MKL-DNN (which uses the deprecated Intel MKL APIs). So you have three options:
- (**recommended**) Update Intel MKL-DNN (maybe to the latest version which is [0.18.1](https://github.com/intel/mkl-dnn/releases/tag/v0.18.1))
- Suppress the `-Wdeprecated`. e.g. by setting replacing
```
set(CMAKE_CCXX_NOWARN_FLAGS)
```
with
```
set(CMAKE_CCXX_NOWARN_FLAGS -Wno-deprecated)
```
in `cmake/platform.cmake`
- Downgrading the Intel MKL library where these functions were not deprecated (<2019U1)
