### ISSUE TITLE
test_reorder fails in v0.9

### ISSUE THREAD

**Issue by luotao1** [01org/mkl-dnn#88] opened 2017-07-06 09:08 UTC
When I `make test` in v0.9, `test_reorder` fails like follows:
```
test 8
    Start 8: test_reorder

8: Test command: /home/luotao/mkl-dnn/build/tests/gtests/test_reorder
8: Test timeout computed to be: 9.99988e+06
8: [==========] Running 30 tests from 3 test cases.
8: [----------] Global test environment set-up.
8: [----------] 24 tests from TestReorder/reorder_simple_test_f32_f32
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/0
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/0 (8 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/1
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/1 (6 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/2
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/2 (5 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/3
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/3 (6 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/4
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/4 (0 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/5
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/5 (1 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/6
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/6 (13 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/7
8: [       OK ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/7 (8 ms)
8: [ RUN      ] TestReorder/reorder_simple_test_f32_f32.TestsReorder/8
1/1 Test #8: test_reorder .....................***Exception: Illegal  0.07 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec

The following tests FAILED:
          8 - test_reorder (ILLEGAL)
Errors while running CTest
make: *** [test] Error 8
```
Can you help me, thx very much!

**Comment by rsdubtso** [comment] 2017-07-06 09:56
Which CPU are you running your tests on? Please post `lscpu` output if it is installed on your machine. (Or, post the output of `cat /proc/cpuinfo`)

**Comment by rsdubtso** [comment] 2017-07-06 10:15
Reproduced on a Sandybridge. Marking as a bug.

**Comment by luotao1** [comment] 2017-07-06 10:19
The output of `cat /proc/cpuinfo` is so long, thus I select the last part of output as follows:
```
processor       : 11
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
stepping        : 7
cpu MHz         : 2001.000
cache size      : 15360 KB
physical id     : 1
siblings        : 6
core id         : 5
cpu cores       : 6
apicid          : 42
initial apicid  : 42
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 x2apic popcnt aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid
bogomips        : 3999.43
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

**Comment by rsdubtso** [comment] 2017-07-06 10:56
Okay, it *is* a Sandybridge. Thanks for the confirmation. I just pulled the latest version from our internal repo and the issue is already fixed. So the fix will be on github soon. The patch is here: https://gist.github.com/rsdubtso/b881384b1f6a8c97d1c7a51aac458ee1

**Closed by rsdubtso** 2017-07-06 10:56 UTC
Labels: bug
